/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package electricitymeters;

package org.nomanspace.electricitymeters;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
